### PR TITLE
Slurm multi version

### PR DESCRIPTION
**Pull request by jspaaks**
This pull request adds an extensible slurm setup. It currently includes files to create docker images with slurm version 14, 15, 16, and 17, each using mysql for their accounting, with all the necessary services in one container (per slurm version). 

The slurm images have a healthcheck defined in the ssh intermediate image. This healthcheck can be used in Xenon integration testing to wait for the container to be fully functional before starting the integration tests.

### CODE REVIEW

**Comment by sverhoeven** [comment]
Please correct the intermediate image names so they can be used as Automated build on Docker Hub.

You have a `FROM xenon-ssh` in `xenon-slurm/xenon-munge/Dockerfile` file, the automated build will fail on this. The images need to be prefixed with a Docker organization `nlesc/`. 

After this we have 2 images with `nlesc/xenon-ssh`, one based on `alpine` and one of yours based on `xenon-supervisor`, this name clash should be resolved by either dropping the `alpine` based image or renaming the `xenon-supervisor` based one.

**Comment by jspaaks** [comment]
Is there any way in which we can just upload/register what we need, without any intermediate images, i.e. what if we just push

- (``nlesc/``)``xenon-slurm-abstract``
- (``nlesc/``)``xenon-slurm-14``
- (``nlesc/``)``xenon-slurm-15``
- (``nlesc/``)``xenon-slurm-16``
- (``nlesc/``)``xenon-slurm-17``

that would mean the information to build any intermediate images is still available, just not from Dockerhub, while avoiding any name clashes.

**Comment by sverhoeven** [comment]
Nope, the automated build requires the FROM image be available on Docker Hub. 

I am OK with replacing the current `nlesc/xenon-ssh` image with yours, as they have the same functionality, only yours is bigger, but the size difference disappears when you also pull a child image. Having the other intermediate images should not be a problem, we could even use them to replace the `xenon-phusion-base` image.

We could use https://github.com/nlesc-sherlock/boatswain and Travis-CI to push the images to Docker Hub, but I dislike this option as the automated build has the less moving parts.

**Comment by jspaaks** [comment]
In summary:

- I flattened the direcotry structure, so each directory in the repo root has its own image on dockerhub
- xenon-slurm-15 has been replaced by the new extensible way
- each README has updated build instructions, where relevant I've added run instructions (xenon-slurm-14, xenon-slurm-15, xenon-slurm-16, xenon-slurm-17)
- added nlesc dockerhub organization in Dockerfile FROM fields
- kept xenon-ssh and xenon-slurm-ssh for the moment.

**Comment by sverhoeven** [comment]
The READMEs in xenon-slurm-* dirs are too minimal. 

For the images that user can use directly add how to start it, login to it and use it. 

For the images which should not be used directly, document this fact and give pointers to images which can be used.

**Pull request merged**
