### PR TITLE
Simplified the slurm stack.

### PR DESCRIPTION
**Pull request by jmaassen**
Removed mysql (could not get it to work) and supervisor because it installed more than 300MB of dependencies.

Simplified the stack to this:
   xenon-slurm-fixtures       
   xenon-slurm-ssh             
   xenon-slurm-abstract
   xenon-slurm-*

The xenon-slurm-abstract now also installs munged and a generic slurm compile script that is used in the xenon-slurm-* versions. 

Final slurm images are now between 409 and 435 MB each (instead of 1.25 GB) and go from start to healthy in 2 seconds. 

Works with Xenon integration tests.

### CODE REVIEW

**Comment by jspaaks** [comment]
Just built the ``nlesc/xenon-slurm-17`` image locally after removing any existing images. Then ran the ``Slurm17SchedulerDockerTest`` from within eclipse. Got one error (``test_getJobStatusses_existingJobs``) and one skipped (``test_interactiveJob_notSupported_throwsException``). My Xenon code is at d8f621b39aca687f50f51df569bf4b2f12df3844.

**Comment by jmaassen** [comment]
The skipped test are expected. They are only run on schedulers that do not support interactive jobs to verify they throw an exception when submitting one. Since slurm does support interactive it skips this test.

Any more information on the error ? You can find an overview in

    ./build/reports/tests/integrationTest/index.html
 
in your xenon directory

**Comment by jspaaks** [comment]
side note: I added python as a dependency because of supervisor. since that's now gone, python is also no longer needed. I build slurm17 and that works without python (although the install of slurm complains about it, I think one of its plugins (that we're not using) needs it.

so in xenon-slurm-abstract/Dockerfile
```diff
-# slurm wants python and munged
-RUN apt-get update && apt-get install -y python munge libmunge2
+# slurm wants munged including its development files
+RUN apt-get update && apt-get install -y munge libmunge2
```

**Comment by jspaaks** [comment]
also I'm guessing we now have one node that's not started on purpose?
sinfo says:
```
PARTITION      AVAIL  TIMELIMIT  NODES  STATE NODELIST
mypartition*      up   infinite      1  down* node-4
mypartition*      up   infinite      4   idle node-[0-3]
otherpartition    up   infinite      3   idle node-[0-2]
```
because xenon-slurm-abstract/start-services.sh starts nodes 0, 1, 2, 3 but not 4.

**Comment by jmaassen** [comment]
Nope, just forgot to add the 4th node. 

But it may be an interesting test case, provided we can get to this information from Xenon in the first place...

**Pull request merged**
